[package]
name = "warrant-canary"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
crypto-hash = "0.3.4"
regex = "1.10.2"
tokio = { version ="1.29.1", features = ["full"] }
reqwest = "0.12.4"
scraper = "0.19.0"
