[package]
name = "warrant-canary"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "6.1.1"
chrono = "0.4.31"
easy-hasher = "2.2.1"
regex = "1.10.2"
tokio = { version ="1.29.1", features = ["full"] }
reqwest = "0.11.22"
scraper = "0.18.1"